server:
  port: 9090
  servlet:
    context-path: /B2CApi-1.0.0
b2capi:
  shortcode: 12345
  email:
password:
  restrict_repeat:
  history_limit:
pin:
  restrict_repeat:
  history_limit:

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    name: /var/logs/b2c.log
    max-size: 20MB
  level:
    root: INFO

jwt:
  token:
    secret: ======================B2cApiApiKoder=Spring===========================
    expirationInMs: 86400000

encdec:
  secret: IXBAJHN3MHJkMHdzJEBwIQ==

onboarding:
  registrationalertid: 100

  authorizationBlue:
    username:
    password:






